# Generated by Django 4.2.5 on 2023-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_table1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_students", models.IntegerField()),
                ("number_of_low_income_students", models.IntegerField()),
                ("year", models.IntegerField()),
                ("percentage_of_low_income_students", models.IntegerField()),
                ("school_number", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Table1",),
    ]
