# Generated by Django 4.2.5 on 2023-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_enrollment_percentage_of_low_income_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("AUN", models.IntegerField()),
                ("school_name", models.CharField(max_length=255)),
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(model_name="enrollment", name="id",),
        migrations.AlterField(
            model_name="enrollment",
            name="school_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
