# Generated by Django 4.2.5 on 2023-11-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("myapp", "0007_keystoneexam_delete_district"),
        ("myapp", "0008_district"),
        ("myapp", "0009_delete_district"),
        ("myapp", "0010_pssaexam_alter_keystoneexam_table"),
        ("myapp", "0011_county_alter_pssaexam_table"),
        ("myapp", "0012_district_alter_county_table"),
        ("myapp", "0013_delete_district_alter_county_table"),
    ]

    dependencies = [
        ("myapp", "0006_rename_aun_school_aun"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeystoneExam",
            fields=[
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
                ("percentage_bio_proficient", models.FloatField()),
                ("percentage_lit_proficient", models.FloatField()),
                ("percentage_alg_proficient", models.FloatField()),
            ],
            options={"db_table": "district",},
        ),
        migrations.DeleteModel(name="District",),
        migrations.CreateModel(
            name="PssaExam",
            fields=[
                ("percentage_eng_proficient", models.FloatField()),
                ("percentage_math_proficient", models.FloatField()),
                ("percentage_science_proficient", models.FloatField()),
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
            ],
            options={"db_table": "district",},
        ),
        migrations.AlterModelTable(name="keystoneexam", table=None,),
        migrations.CreateModel(
            name="County",
            fields=[
                ("county_id", models.IntegerField(primary_key=True, serialize=False)),
                ("county_name", models.CharField(max_length=255)),
            ],
            options={"db_table": "district",},
        ),
        migrations.AlterModelTable(name="pssaexam", table=None,),
        migrations.AlterModelTable(name="county", table="district",),
    ]
