# Generated by Django 4.2.5 on 2023-12-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_keystoneexam_school_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictF",
            fields=[
                ("county_n", models.CharField(max_length=255)),
                ("d_id", models.IntegerField(primary_key=True, serialize=False)),
                ("d_name", models.CharField(max_length=255)),
            ],
        ),
    ]
