# Generated by Django 4.2.5 on 2023-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_districtf"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="elementary_school",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="high_school",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="middle_school",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
