# Generated by Django 4.2.5 on 2023-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_keystoneexam_delete_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(db_column="district_name", max_length=255),
                ),
            ],
        ),
    ]
