# Generated by Django 4.2.5 on 2023-11-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_district"),
    ]

    operations = [
        migrations.DeleteModel(name="District",),
    ]
