# Generated by Django 4.2.5 on 2023-11-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_delete_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="PssaExam",
            fields=[
                ("percentage_eng_proficient", models.FloatField()),
                ("percentage_math_proficient", models.FloatField()),
                ("percentage_science_proficient", models.FloatField()),
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
            ],
            options={"db_table": "district",},
        ),
        migrations.AlterModelTable(name="keystoneexam", table=None,),
    ]
