# Generated by Django 4.2.5 on 2023-11-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_delete_district_alter_county_table"),
    ]

    operations = [
        migrations.RenameModel(old_name="County", new_name="CountyModel",),
    ]
