# Generated by Django 4.2.5 on 2023-11-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_rename_county_countymodel"),
    ]

    operations = [
        migrations.DeleteModel(name="CountyModel",),
        migrations.AlterModelTable(name="pssaexam", table="district",),
    ]
