# Generated by Django 4.2.5 on 2023-11-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_delete_countymodel_alter_pssaexam_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountyModel",
            fields=[
                ("county_id", models.IntegerField(primary_key=True, serialize=False)),
                ("county_name", models.CharField(max_length=255)),
            ],
            options={"db_table": "district",},
        ),
        migrations.AlterModelTable(name="pssaexam", table=None,),
    ]
