# Generated by Django 4.2.5 on 2023-11-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_countymodel_alter_pssaexam_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="countymodel", table="myapp_custom_county",),
    ]
