# Generated by Django 4.2.5 on 2023-11-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_countymodel_table"),
    ]

    operations = [
        migrations.DeleteModel(name="CountyModel",),
        migrations.AlterModelTable(name="pssaexam", table="myapp_custom_county",),
    ]
