# Generated by Django 4.2.5 on 2023-11-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_delete_countymodel_alter_pssaexam_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="pssaexam", table=None,),
    ]
